SST Errors Package Bulk
SalientSys/salient-sst-errors pull request #1
Opened 2022-11-30 20:37 UTC by SohailHaqyar

2022-12-02 19:29 UTC, zbagley commented on LICENSE
> +MIT License
Are we required to do MIT License, or can we do something slightly more proprietary. At least an Apache 2.0, but preferably a non-commercial clause like the GNU GPL.

2022-12-02 19:31 UTC, zbagley commented
This one is a pretty massive PR, daunting, and it's no wonder why you don't have a reviewer yet! It might make sense to get one or two of the other key devs into a sync so you could cover some key points verbally.

2022-12-05 16:23 UTC, TonyH-Salient commented on LICENSE
> +MIT License
The license can be any of OSI approved licenses. It defaults to ISC. And yes, we can use GNU GPL as described in the list here https://choosealicense.com/licenses/

2022-12-05 20:50 UTC, TonyH-Salient requested changes

2022-12-05 20:50 UTC, TonyH-Salient commented on src/shared/exceptions/next.decorator.ts
> +export function Next(
This `Next()` and its usage `@Next()` is applicable only to back-end and should not be placed in this npm package

2022-12-05 20:50 UTC, TonyH-Salient commented on src/services/organization-exceptions.ts
> +      entity === OrganizationType.EndUser
`scs-dto` should be the only place to have `OrganizationType` (in the spirit of `single source of truth`)
This just adds in another reason on @Next() should not reside in this package

2022-12-05 20:50 UTC, TonyH-Salient commented on src/shared/error-code-generator.ts
> +const generateErrorCode = (
Can you leave some document on how the result error code looks like? E.g: How to parse an error code from a consumer perspective? Each component/part of the error code and how many digits/number per each part?

2022-12-05 20:50 UTC, TonyH-Salient commented on src/shared/routes-map.ts
> +  acc[val] = i + 100;
Does this mean the route portion of an error code is a 3-digit number whereas other portions has 5 digits?

2022-12-05 21:08 UTC, TonyH-Salient commented on src/factory-functions/get-in-service-error-handler.ts
> +const getErrorHandler = () => {
What is the difference between errorHandler and exceptionHandler?

2022-12-05 21:23 UTC, TonyH-Salient commented on src/factory-functions/get-exception-handler.ts
> +export const xH = new Exceptions(
A descriptive name is preferred over abbreviation. 

Also, the name `exceptionHandler` doesn't make much sense because this class is doesn't strike me as a handler. An error handler is something we have in the back-end side (`errorMiddleware`) where the error being processed (sent to the client). The middleware and controllers, in the other hand, are responsible for funneling the error to that single handler.
`ErrorFactor` perhaps?

This class is a composition of different errors, and

2022-12-05 22:43 UTC, MatthewMerc commented on src/shared/routes-map.ts
> +  acc[val] = i + 100;
That's correct, IIUC. The file that parses the errorCode back into a friendly message makes it relatively clear. From my review notes, it's an ongoing task to swap out the number with constants that provide more context.

2022-12-05 22:46 UTC, MatthewMerc commented on src/factory-functions/get-exception-handler.ts
> +export const xH = new Exceptions(
Agreed with the later points, but fwiw, I think an abbreviated name is fine in this case, as this const is used _everywhere_ in the back-end, so I don't think it would be very unclear what `xH` (or whatever the future name would be) is.

2022-12-07 02:48 UTC, SohailHaqyar commented on src/shared/enums/route-names.enum.ts
> +  PostDeploymentByIdInviteIntegrator = '[POST]/deployment-instances/:deploymentId/invite-integrator',
Done; a6b317d29703e453f7c25c795dc9a0db0e887068

2022-12-07 02:48 UTC, SohailHaqyar commented on src/shared/enums/route-names.enum.ts
> +  PostDeploymentRequestToBeIntegrator = '[POST]/deployment-instances/request-to-be-integrator',
Done; a6b317d29703e453f7c25c795dc9a0db0e887068

2022-12-07 02:54 UTC, SohailHaqyar commented on src/shared/enums/error-reasons.enum.ts
> +export enum ErrorReasons {
Done;https://github.com/SalientSys/salient-sst-errors/commit/a6b317d29703e453f7c25c795dc9a0db0e887068

2022-12-07 02:54 UTC, SohailHaqyar commented on src/shared/enums/error-reasons.enum.ts
> +  EndUserNotAssociatedWithIntegrator = 'End-user is not associated with integrator organization.',
https://github.com/SalientSys/salient-sst-errors/commit/a6b317d29703e453f7c25c795dc9a0db0e887068
Done

2022-12-07 02:55 UTC, SohailHaqyar commented on src/shared/enums/middlewares.enum.ts
> +export enum Middlewares {
Yup https://github.com/SalientSys/salient-sst-errors/commit/a6b317d29703e453f7c25c795dc9a0db0e887068

2022-12-07 02:55 UTC, SohailHaqyar commented on src/shared/enums/services.enum.ts
> +export enum Services {
https://github.com/SalientSys/salient-sst-errors/commit/a6b317d29703e453f7c25c795dc9a0db0e887068

2022-12-07 02:57 UTC, SohailHaqyar commented on src/shared/error-code-generator.ts
> +const generateErrorCode = (
a3f6f69

2022-12-08 17:13 UTC, SohailHaqyar commented on LICENSE
> +MIT License
Done;[d169f95](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/d169f95fa16a731145b651e38b86eec53130e5f8)

2022-12-08 17:35 UTC, TonyH-Salient commented on package.json
> +  "license": "MIT",
This one needs updating as well `GNU GPLv3`

2022-12-08 17:40 UTC, TonyH-Salient commented on src/parse-error.ts
> +  service: { name: string; code: number };
NIT: Can we define an interface for theses? `ErrorPortion` perhaps?
That will help the consumption in the front-end side

2022-12-08 17:50 UTC, MatthewMerc requested changes

2022-12-08 17:50 UTC, MatthewMerc commented on src/parse-error.ts
> +  service: { name: string; code: number };
+1 here

2022-12-08 17:50 UTC, MatthewMerc commented on src/parse-error.ts
> +const MIDDLEWARE_LENGTH_END = 8;
Not sure if it's actually used, but for the sake of completion, could you add `const SERVICE_LENGTH_END = 2` also here?

2022-12-08 17:50 UTC, MatthewMerc commented on src/parse-error.ts
> +      route: { name: '', code: -1 },
It might be worth creating a new string const along the lines of `const PARSE_ERROR_NAME = 'unable to parse error code`` here and use that for when parsing fails.

2022-12-08 17:50 UTC, MatthewMerc commented on src/parse-error.ts
> +  );
We might still need one final check here to ensure that the route,middleware,service names are all correctly parsed here.

2022-12-08 17:51 UTC, TonyH-Salient commented on src/parse-error.ts
> +const FULL_CODE_LENGTH = 13;
NIT: The values for lengths is preferred over their indices in the array.

```
const ROUTE_CODE_LENGTH = 3;
const MIDDLEWARE_CODE_LENGTH = 5;
const SERVICE_CODE_LENGTH=5;

let index = 0;
const routeCode = parseInt(stringified.substring(index, ROUTE_CODE_LENGTH));
index += ROUTE_CODE_LENGTH;
const middlewareCode = parseInt(stringified.substring(index, MIDDLEWARE_CODE_LENGTH));
index += MIDDLEWARE_CODE_LENGTH;
const serviceCode = parseInt(stringified.substring(index, SERVICE_CODE_LENGTH));
```

2022-12-08 22:06 UTC, SohailHaqyar commented on src/parse-error.ts
> +const FULL_CODE_LENGTH = 13;
Awesome Idea. [1b418d5](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/1b418d562ff05fb9f65436c34da1a1b01a8b3d3f)

2022-12-08 22:12 UTC, SohailHaqyar commented on src/parse-error.ts
> +  );
[867096a](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/867096a305e290b84a97abbb22469490b8203f51)

2022-12-08 22:12 UTC, SohailHaqyar commented on src/parse-error.ts
> +      route: { name: '', code: -1 },
[867096a](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/867096a305e290b84a97abbb22469490b8203f51)

2022-12-08 22:12 UTC, SohailHaqyar commented on src/parse-error.ts
> +const MIDDLEWARE_LENGTH_END = 8;
[1b418d5](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/1b418d562ff05fb9f65436c34da1a1b01a8b3d3f)

2022-12-08 22:12 UTC, SohailHaqyar commented on src/parse-error.ts
> +  service: { name: string; code: number };
[1b418d5](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/1b418d562ff05fb9f65436c34da1a1b01a8b3d3f)

2022-12-08 22:13 UTC, SohailHaqyar commented on .gitignore
> +# Logs
[1b418d5](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/1b418d562ff05fb9f65436c34da1a1b01a8b3d3f)

2022-12-08 22:17 UTC, TonyH-Salient approved these changes

2022-12-09 20:42 UTC, dante-salient commented on .gitignore
> +.DS_STORE
src/DS_Store also needed

2022-12-09 20:46 UTC, dante-salient commented on src/enums/middlewares.enum.ts
> +export enum Middleware {
Naming is a bit ambiguous imo. Could we rename to MiddlewareCodes or add some other context to it

2022-12-09 20:48 UTC, TonyH-Salient commented on src/enums/middlewares.enum.ts
> +export enum Middleware {
`MiddlewareCode` is actually a good name. We don't use plural form on enum FYI

2022-12-09 20:49 UTC, dante-salient commented on src/enums/services.enum.ts
> +export enum Service {
Same comment as before. Add some code context.

2022-12-12 14:41 UTC, SohailHaqyar commented on .gitignore
> +.DS_STORE
[18368c9](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/18368c9e713988a9d062924b1da04baab48fe102)

2022-12-12 14:43 UTC, SohailHaqyar commented on src/enums/services.enum.ts
> +export enum Service {
[bdb24bf](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/bdb24bf577039f4c09d9ee28c5123282d061f867)

2022-12-12 14:43 UTC, SohailHaqyar commented on src/enums/middlewares.enum.ts
> +export enum Middleware {
[bdb24bf](https://github.com/SalientSys/salient-sst-errors/pull/1/commits/bdb24bf577039f4c09d9ee28c5123282d061f867)

2022-12-12 14:44 UTC, merged