Jira/cld 962
SalientSys/salient-sst-errors pull request #6
Opened 2023-02-15 16:15 UTC by SohailHaqyar

2023-02-15 17:05 UTC, EthanFlower1 commented on src/enums/route-names.enum.ts
> +  DeploymentAdminVpnUsers = '[GET]/deployments/admin/:deploymentId/vpn-users*',
NIT: Maybe this is better worded as adminGetDeploymentVpnUsers?

2023-02-16 23:43 UTC, TonyH-Salient requested changes

2023-02-16 23:43 UTC, TonyH-Salient commented on src/enums/middlewares.enum.ts
> +  GetVpnUsersHandler = 10099,
It might be worth it to add `Deployment` into these names

`GetDeploymentProxyLogsHandler`
`RestartDeploymentVpnHandler`
`GetDeploymentVpnUsersHandler`

2023-02-16 23:43 UTC, TonyH-Salient commented on src/enums/route-names.enum.ts
> +  AdminPutDeploymentRestartVpn = '[PUT]/deployments/admin/:deploymentId/restart-vpn*',
We can go ahead and `Admin` from the name

2023-02-16 23:43 UTC, TonyH-Salient commented on src/enums/route-names.enum.ts
> +  AdminGetDeploymentRemoteAccessLogs = '[GET]/deployments/admin/:deploymentId/remote-access-logs',
`GetDeploymentProxyLogs`

2023-02-16 23:43 UTC, TonyH-Salient commented on src/enums/services.enum.ts
> +  RequestQueryService = 10023,
Probably not needed

2023-02-20 14:56 UTC, SohailHaqyar commented on src/enums/services.enum.ts
> +  RequestQueryService = 10023,
[2f42a6b](https://github.com/SalientSys/salient-sst-errors/pull/6/commits/2f42a6b3b0771dbf6769922ff51b114c349779cb)

2023-02-20 14:57 UTC, SohailHaqyar commented on src/enums/route-names.enum.ts
> +  AdminGetDeploymentRemoteAccessLogs = '[GET]/deployments/admin/:deploymentId/remote-access-logs',
[2f42a6b](https://github.com/SalientSys/salient-sst-errors/pull/6/commits/2f42a6b3b0771dbf6769922ff51b114c349779cb)

2023-02-20 14:59 UTC, SohailHaqyar commented on src/enums/middlewares.enum.ts
> +  GetVpnUsersHandler = 10099,
[0772b34](https://github.com/SalientSys/salient-sst-errors/pull/6/commits/0772b34409de086ac47cdb002b2cf5594af36e6a)

2023-02-20 15:54 UTC, merged